### ISSUE TITLE
No way to test hooks or components — only pure logic

### ISSUE THREAD

**Issue by Abuubkar** [hedonarc/foodio#18]
## Problem

The repo can test pure functions and Zustand stores, and does — 90 tests. It cannot test anything that renders.

AGENTS.md asks for tests over "business logic, hooks, utilities". Hooks are currently uncovered because there is no renderer.

## What was tried

Adding `@testing-library/react-native@14.0.1` for a `useDebounce` test. v14 makes `renderHook` async and its types did not resolve against this Jest/TS setup:

```
Property 'rerender' does not exist on type 'Promise<RenderHookResult<unknown, unknown>>'
```

Rather than ship an unused dependency or a broken test, both were removed in #17.

## Why it matters

Untested today as a direct result:

- `useDebounce`
- `useCurrentCoordinates` — permission denial and location failure paths
- `useOrder` — the polling that stops at a terminal status
- every screen's loading, error and empty branch

The `reviewCheckout` rules are well covered precisely *because* they were designed as a pure function. That was the right call, but it does not extend to hooks that hold state.

## Acceptance criteria

- [ ] `renderHook` works against this Jest config, with a passing test for `useDebounce`
- [ ] One component test renders a screen and asserts its loading, error and empty branches
- [ ] `pnpm test` still runs clean in CI
- [ ] Whatever version pins are needed are recorded, since RNTL 14 + jest-expo 57 + React 19 is the combination that broke

## Notes

`jest-expo` is pinned at 57.0.3 and jest at 29 because jest-expo 57 depends on jest 29 internals — a jest 30 install produced `this._moduleMocker.clearMocksOnScope is not a function`. Worth checking whether RNTL 14 expects jest 30.
